/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author andre
 */
public class MenuPrincipalBarbearia extends javax.swing.JFrame {
    
    private static final Color COR_PAINEL_BOTAO = new Color(13, 71, 161); // Azul escuro
    private static final Color COR_PAINEL_BOTAO_HOVER = new Color(21, 101, 192); // Azul mais claro para hover
    private static final Color COR_TEXTO = Color.WHITE;
    private static final Font FONTE_BOTAO = new Font("Segoe UI", Font.BOLD, 16);
    private static final Font FONTE_ICONE = new Font("Segoe UI Symbol", Font.PLAIN, 48); // Fonte que suporta ícones unicode
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalBarbearia.class.getName());

    /**
     * Creates new form MenuPrincipalBarbearia
     */
    public MenuPrincipalBarbearia() {
    initComponents();

    // Força o painel principal a usar BorderLayout
    jPanel2.setLayout(new BorderLayout());

    // Coloca o título no topo
    jPanel2.add(jLabel1, BorderLayout.NORTH);

    // Configura espaçamento e grade para os botões
    jPanelDashboard.setBorder(new EmptyBorder(20, 20, 20, 20));
    jPanelDashboard.setLayout(new GridLayout(0, 3, 20, 20));

    // Adiciona o painel de botões no centro
    jPanel2.add(jPanelDashboard, BorderLayout.CENTER);

    // Criação dos botões
    jPanelDashboard.add(criarBotaoFuncionalidade("Agendamento", "\uD83D\uDCC6"));
    jPanelDashboard.add(criarBotaoFuncionalidade("Estoque", "\uD83D\uDCE6"));
    jPanelDashboard.add(criarBotaoFuncionalidade("Faturamento", "\uD83D\uDCCA"));
    jPanelDashboard.add(criarBotaoFuncionalidade("Despesas", "\uD83D\uDCB8"));
    jPanelDashboard.add(criarBotaoFuncionalidade("Cadastro de Produtos", "➕"));
    jPanelDashboard.add(criarBotaoFuncionalidade("Cadastro de Despesas", "✎"));

    setTitle("Dashboard - Sistema de Barbearia");
    setSize(1000, 800);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setLocationRelativeTo(null);
}

    
    private JPanel criarBotaoFuncionalidade(String texto, String iconeUnicode) {
        JPanel painel = new JPanel();
        painel.setLayout(new BorderLayout());
        painel.setBackground(COR_PAINEL_BOTAO);
        painel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // Borda arredondada (simulada com EmptyBorder)
        Border margem = new EmptyBorder(15, 15, 15, 15);
        Border bordaComposta = BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(COR_PAINEL_BOTAO, 10, true), // Simula o arredondamento
            margem
        );
        painel.setBorder(bordaComposta);

        // Ícone
        JLabel iconeLabel = new JLabel(iconeUnicode, SwingConstants.CENTER);
        iconeLabel.setFont(FONTE_ICONE);
        iconeLabel.setForeground(COR_TEXTO);

        // Texto
        JLabel textoLabel = new JLabel(texto, SwingConstants.CENTER);
        textoLabel.setFont(FONTE_BOTAO);
        textoLabel.setForeground(COR_TEXTO);

        painel.add(iconeLabel, BorderLayout.CENTER);
        painel.add(textoLabel, BorderLayout.SOUTH);

        // Adicionar eventos do mouse
        painel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Efeito hover ao entrar o mouse
                painel.setBackground(COR_PAINEL_BOTAO_HOVER);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Volta à cor original ao sair
                painel.setBackground(COR_PAINEL_BOTAO);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                // Ação ao clicar no painel
                JOptionPane.showMessageDialog(
                    MenuPrincipalBarbearia.this,
                    "Abrindo a tela de: " + texto,
                    "Navegação",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        });

        return painel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDashboard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBackground(new java.awt.Color(204, 204, 204));
        dashboardPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 71, 161));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gemini_Generated_Image_8n3h3u8n3h3u8n3h.png"))); // NOI18N

        jPanelDashboard.setMaximumSize(null);

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(171, 171, 171))
            .addComponent(jPanelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dashboardPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalBarbearia().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDashboard;
    // End of variables declaration//GEN-END:variables
}
